Execute specs w/ webpack using > jasmine-flight@4.0.0 test-webpack /Users/andrew/Projects/personal/jasmine-flight > karma start karma-webpack.conf.js --single-run
[32mINFO [karma]: [39mKarma v0.12.24 server started at http://localhost:9876/
[32mINFO [launcher]: [39mStarting browser Chrome
[32mINFO [Chrome 39.0.2171 (Mac OS X 10.9.5)]: [39mConnected on socket GONdH_eGFVlJhazMxtmE with id 49657519
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 0 of 35[32m SUCCESS[39m (0 secs / 0 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 1 of 35[32m SUCCESS[39m (0 secs / 0.005 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 2 of 35[32m SUCCESS[39m (0 secs / 0.007 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 3 of 35[32m SUCCESS[39m (0 secs / 0.011 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 4 of 35[32m SUCCESS[39m (0 secs / 0.011 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 5 of 35[32m SUCCESS[39m (0 secs / 0.012 secs)
[1A[2K[31mChrome 39.0.2171 (Mac OS X 10.9.5)  defineComponent.teardownAll() automatically calls after each test first call FAILED[39m
	Expected 0 to equal 1.
	Error: Expected 0 to equal 1.
	    at Object.<anonymous> (/Users/andrew/Projects/personal/jasmine-flight/test/spec/describe_component.spec.js:97:34)
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 6 of 35[31m (1 FAILED)[39m (0 secs / 0.015 secs)
[1A[2K[31mChrome 39.0.2171 (Mac OS X 10.9.5)  defineComponent.teardownAll() automatically calls after each test second call FAILED[39m
	Expected 0 to equal 2.
	Error: Expected 0 to equal 2.
	    at Object.<anonymous> (/Users/andrew/Projects/personal/jasmine-flight/test/spec/describe_component.spec.js:101:34)
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 7 of 35[31m (2 FAILED)[39m (0 secs / 0.017 secs)
[1A[2K[31mChrome 39.0.2171 (Mac OS X 10.9.5)  defineComponent.teardownAll() automatically calls after each test third call FAILED[39m
	Expected 0 to equal 3.
	Error: Expected 0 to equal 3.
	    at Object.<anonymous> (/Users/andrew/Projects/personal/jasmine-flight/test/spec/describe_component.spec.js:105:34)
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 8 of 35[31m (3 FAILED)[39m (0 secs / 0.02 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 9 of 35[31m (3 FAILED)[39m (0 secs / 0.021 secs)
[1A[2K[31mChrome 39.0.2171 (Mac OS X 10.9.5)  this.component.teardown() should be called by afterEach of before `it` FAILED[39m
	Expected 1 to equal 3.
	Error: Expected 1 to equal 3.
	    at Object.<anonymous> (/Users/andrew/Projects/personal/jasmine-flight/test/spec/describe_component.spec.js:128:32)
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 10 of 35[31m (4 FAILED)[39m (0 secs / 0.022 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 11 of 35[31m (4 FAILED)[39m (0 secs / 0.023 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 12 of 35[31m (4 FAILED)[39m (0 secs / 0.024 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 13 of 35[31m (4 FAILED)[39m (0 secs / 0.024 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 14 of 35[31m (4 FAILED)[39m (0 secs / 0.025 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 15 of 35[31m (4 FAILED)[39m (0 secs / 0.028 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 16 of 35[31m (4 FAILED)[39m (0 secs / 0.029 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 17 of 35[31m (4 FAILED)[39m (0 secs / 0.03 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 18 of 35[31m (4 FAILED)[39m (0 secs / 0.031 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 19 of 35[31m (4 FAILED)[39m (0 secs / 0.032 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 20 of 35[31m (4 FAILED)[39m (0 secs / 0.033 secs)
[1A[2K[31mChrome 39.0.2171 (Mac OS X 10.9.5)  defineComponent.teardownAll() automatically calls after each test first call FAILED[39m
	Expected 0 to equal 1.
	Error: Expected 0 to equal 1.
	    at Object.<anonymous> (/Users/andrew/Projects/personal/jasmine-flight/test/spec/describe_mixin.spec.js:71:34)
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 21 of 35[31m (5 FAILED)[39m (0 secs / 0.035 secs)
[1A[2K[31mChrome 39.0.2171 (Mac OS X 10.9.5)  defineComponent.teardownAll() automatically calls after each test second call FAILED[39m
	Expected 0 to equal 2.
	Error: Expected 0 to equal 2.
	    at Object.<anonymous> (/Users/andrew/Projects/personal/jasmine-flight/test/spec/describe_mixin.spec.js:75:34)
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 22 of 35[31m (6 FAILED)[39m (0 secs / 0.035 secs)
[1A[2K[31mChrome 39.0.2171 (Mac OS X 10.9.5)  defineComponent.teardownAll() automatically calls after each test third call FAILED[39m
	Expected 0 to equal 3.
	Error: Expected 0 to equal 3.
	    at Object.<anonymous> (/Users/andrew/Projects/personal/jasmine-flight/test/spec/describe_mixin.spec.js:79:34)
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 23 of 35[31m (7 FAILED)[39m (0 secs / 0.036 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 24 of 35[31m (7 FAILED)[39m (0 secs / 0.038 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 25 of 35[31m (7 FAILED)[39m (0 secs / 0.038 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 26 of 35[31m (7 FAILED)[39m (0 secs / 0.039 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 27 of 35[31m (7 FAILED)[39m (0 secs / 0.04 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 28 of 35[31m (7 FAILED)[39m (0 secs / 0.041 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 29 of 35[31m (7 FAILED)[39m (0 secs / 0.042 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 30 of 35[31m (7 FAILED)[39m (0 secs / 0.044 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 31 of 35[31m (7 FAILED)[39m (0 secs / 0.047 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 32 of 35[31m (7 FAILED)[39m (0 secs / 0.048 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 33 of 35[31m (7 FAILED)[39m (0 secs / 0.049 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 34 of 35[31m (7 FAILED)[39m (0 secs / 0.05 secs)
[1A[2K[31mChrome 39.0.2171 (Mac OS X 10.9.5) mock/example_module requires module and sets this.module FAILED[39m
	Expected undefined to be true.
	Error: Expected undefined to be true.
	    at Object.<anonymous> (/Users/andrew/Projects/personal/jasmine-flight/test/spec/describe_module.spec.js:57:36)
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 35 of 35[31m (8 FAILED)[39m (0 secs / 0.051 secs)
[1A[2KChrome 39.0.2171 (Mac OS X 10.9.5): Executed 35 of 35[31m (8 FAILED)[39m (0.055 secs / 0.051 secs)